spring:
    datasource:
        url: jdbc:mysql://localhost:3306/tecwebike?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
        username: root
        password: 123456789